version: '3.7'
services:
    license_server:
        image: liumuqing/ida_license_server
        restart: always
        mac_address: ${MAC_ADDRESS}
        networks:
            - internal
        expose:
            - "8090"
            - "26999"
            - "27000"
    proxy_27000:
        restart: always
        depends_on:
            - license_server
        image: alpine/socat
        restart: always
        networks:
            - internal
            - external
        command:
            - tcp-listen:27000,fork
            - tcp-connect:license_server:27000
        ports:
            - 27000:27000
    proxy_8090:
        restart: always
        depends_on:
            - license_server
        image: alpine/socat
        restart: always
        networks:
            - internal
            - external
        command:
            - tcp-listen:8090,fork
            - tcp-connect:license_server:8090
        ports:
            - 8090:8090
    proxy_26999:
        restart: always
        depends_on:
            - license_server
        image: alpine/socat
        restart: always
        networks:
            - internal
            - external
        command:
            - tcp-listen:26999,fork
            - tcp-connect:license_server:26999
        ports:
            - 26999:26999
networks:
    internal:
        internal: true
    external: {}
